### ISSUE TITLE
STORE command error: BAD ['[CLIENTBUG] STORE Bad sequence in the command']

### ISSUE THREAD

**Issue by MoeRice** [MoeRice/AOL_SPAM_DELETE#1]
Traceback (most recent call last):
  File "C:\Email Spam Delete\Imap.py", line 14, in <module>
    con.store(num, '+FLAGS', '\\Deleted $Junk')
  File "C:\Python27\lib\imaplib.py", line 734, in store
    typ, dat = self._simple_command('STORE', message_set, command, flags)
  File "C:\Python27\lib\imaplib.py", line 1088, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Python27\lib\imaplib.py", line 918, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
error: STORE command error: BAD ['[CLIENTBUG] STORE Bad sequence in the command']

After a certain amount of emails get this error.

Script completes if you run it again. Still trying to see what I can do.

**Comment by MoeRice** [comment]
Re did some of the logic. Dont have any errors now.
